

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: transactions-gateway
spec:
  selector:
    {{- include "net-transactions.selectorLabels" . | nindent 6 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"